#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

echo "${YELLOW}Cleaning up old generations...${NC}"
nix-collect-garbage -d
sudo nix-collect-garbage -d

echo "${GREEN}Cleanup complete!${NC}"
