#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

echo "${YELLOW}Rolling back to previous generation...${NC}"
sudo darwin-rebuild --rollback

echo "${GREEN}Rollback complete!${NC}"
